- Scripts/Nelderim/Quest/DrunkFishermanQuest/DrunkFishermanQuest.cs
- Scripts/Nelderim/Quest/DrunkFishermanQuest/DrunkMinersPickaxe.cs
- Scripts/Nelderim/Quest/DrunkFishermanQuest/EarringsOfTheMinersFormerWife.cs
- dodane cliloci
- dostosowane teksty
- bedzie wykonywany raz
- odmawia graczowi ponownego wykonania
> Drunk fisherman quest

- Scripts/Services/BulkOrders/Items/PowderOfFortKeg.cs
Keg przyjmuje różne typy SpecializedPowderOfTemperament.
Keg nie pozwoli na włożenie innego typu proszku, gdy już składowany jest inny.
Keg pozowli na włożenie innego typu po opróżnieniu kega.
Keg opróżniany jest po 1 sztuce proszku.
Napełniać można keg w plecaku i na glebie. Opróżniać tylko można, gdy mamy keg w plecaku.
> Reworked PowderOfFortKeg.cs for SpecializedPowderOfTemperament

- Scripts/VendorInfo/SBShipwright.cs
Dodano Ogromny Galeon do Shipwrighta, dodano orczy galeon i wykomentowano. Ustalono ceny okrętów.
> Dodano Ogromny Galeon (BritannianShipDeed) do kupna, ustalono ceny statków i okrętów. Dodano i wykomentowano orczy galeon.

- Data/CliLoc.csv
> Poprawki cliloca

- Data/CliLoc.csv
Poprawki i tłumaczenia statki, ksiega nekro
> Tłumaczenia i poprawki

- Data/CliLoc.csv
Poprawki w nazwach czapek, spodni i koszul
> Poprawki cliloc krawiec

- Data/CliLoc.csv
- Scripts/Services/Craft/DefTailoring.cs
Poprawki w CliLoc.csv, dodanie brakujacych nazw, uporzadkowanie DefTailoring.cs, wykontowanie craftowalnych artów.
> Cliloc oraz def tailoring.cs

- Config/Server.cfg
- Data/CliLoc.csv
- Scripts/Items/Containers/Container.cs
- Scripts/Items/Containers/FancyElvenArmoire.cs
- Scripts/Items/Containers/FurnitureContainer.cs
- Scripts/Items/Decorative/Chairs.cs
- Scripts/Items/Decorative/Stools.cs
- Scripts/Items/Decorative/Thrones.cs
- Scripts/Items/Decorative/UpholsteredChair.cs
- Scripts/Services/Craft/DefCarpentry.cs
Zmiany w menu stolarza, clilocach i wagach itemow
> Zmiany w menu stolarza, clilocach i wagach itemow

- Scripts/Nelderim/Items/Artifacts/Baronowa/Artifact_AchillesSpear.cs
- Scripts/Nelderim/Items/Artifacts/Baronowa/Artifact_Annihilation.cs
- Scripts/Nelderim/Items/Artifacts/Baronowa/Artifact_ArcaneArms.cs
- Scripts/Nelderim/Items/Artifacts/Baronowa/Artifact_BraceletOfTheElements.cs
- Scripts/Nelderim/Items/Artifacts/Baronowa/Artifact_InquisitorsHelm.cs
- Scripts/Nelderim/Items/Artifacts/Baronowa/Artifact_SinbadsSword.cs
Pierwsza porcja artów z bossa Baronowej. Jeszcze ich nie wpinam w bossa
> Baronowa porcja artów

- Data/CliLoc.csv
- Data/Regions/Felucca.xml
- Scripts/Mobiles/Normal/ElderGazer.cs
- Scripts/Mobiles/Normal/Gazer.cs
- Scripts/Mobiles/Normal/RevenantLion.cs
- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/Burugh/BurughAltar.cs
- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/Burugh/BurughKey.cs
- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/Burugh/KielBiesa.cs
- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/Burugh/OdnogaGazera.cs
- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/Burugh/PowiekaGazera.cs
- Scripts/Nelderim/Mobiles/Monsters/MigBoss/NBurugh.cs
- przetłumaczono informacje z cliloc odnoszące się do systemu Peerless
- stworzono klucze i ołtarz dla Burugha
- Burugh jest od teraz BasePeerless
> Burugh Turned Into Peerless

- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/ArcaneTunic.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/AzysBracelet.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/BeaconOfHope.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/Beastmaster.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/Clasp.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/EarringsOfTheMagician.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/EverlastingBottle.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/KopmendiumWiedzyDrowow.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/ObronaZywiolow.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/PancerzPrzodkaCzystejKrwi.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/RodOfResurrection.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/SoulRipper.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/StaffofSnakes.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/WidowMorphingArmor/WidowCloak.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/WidowMorphingArmor/WidowMorphArms.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/WidowMorphingArmor/WidowMorphChest.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/WidowMorphingArmor/WidowMorphGloves.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/WidowMorphingArmor/WidowMorphGorget.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/WidowMorphingArmor/WidowMorphHelm.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/WidowMorphingArmor/WidowMorphLegs.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/WidowMorphingArmor/WidowSpawn.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/WyzywajaceOdzienieBarbarzyncy.cs
- Scripts/Nelderim/Items/Artifacts/ZleceniaBossy/gluttonousblade.cs
- Scripts/Nelderim/Items/BaseMagicObject.cs
- Scripts/Nelderim/Items/MagicObjectTarget.cs
on Jan 20, 2024
Aretfakty, które na pewno jeszcze są do poprawki, ale nie potrafię tego zrobić:
ObronaZywiolow (efekt odbijania obrazen nie znika, po zdjeciu tarczy)
ten set Widow (nie przywołuje tej wdowy) -> generalnie nie wiem czy całego setu nie wyjebać, sam mechanizm przywoływania nie jest konieczny i jak set będzie ok, może funkcjonować w tej postaci, tylko dokręcić po testach trzeba cyferki ewentualnie
Do sprawdzenia:
timery w artach, czy nie zjadają zbytnio zasobów (szczególnie w kolczykach i gluttonousblade)
Na pewno są ok, bo są czyste, bez dodatkowych mechanik:
BeaconOfHope
Clasp
EverlastingBottle
Inne arty z mechanikami bez timerów zdają się działać ok
on Sep 11, 2024
Zrobiłem więcej poprawek tych timerów. Można przeglądnąć i daj znać @kaczy93  czy jest ok
> HB Boss Artifacts

- Scripts/Mobiles/Bosses/ChiefParoxysmus.cs
- Scripts/Mobiles/Bosses/DreadHorn.cs
- Scripts/Mobiles/Bosses/LadyMelisande.cs
- Scripts/Mobiles/Bosses/MonstrousInterredGrizzle.cs
- Scripts/Mobiles/Bosses/ShimmeringEffusion.cs
- Scripts/Mobiles/Bosses/Travesty.cs
- Scripts/Mobiles/Named/Meraktus.cs
Ustanowiono drop talizmanów z peerlessów na 5%
Zmieniono drop PeerlessResource na 2
> Drop talizmanów i peerlessresource

- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/Burugh/BurughAltar.cs
- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/ExodusBoss/ExodusBossAltar.cs
- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/ImiennySmok/ImiennySmokAltar.cs
- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/KoscianySmok/KoscianegoSmokAltar.cs
- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/Sarag/SaraAltar.cs
- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/StarozytnyDiamentowySmok/StarozytnyDiamentowySmokAltar.cs
- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/StarozytnyLodowySmok/StarozytnyLodowySmokAltar.cs
- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/StarozytnyOgnistySmok/StarozytnyOgnistySmokAltar.cs
Ustawiono takie hue jak bylo dobrane w grze.
> Altars Hue Fix

- Scripts/Mobiles/AI/Magical AI/PaladinAI.cs
AIowane.
Added a check using var isRevenant = bc is Revenant; to determine if the target is a Revenant Added a cooldown timer:
Created a private DateTime field m_NextDispelTime to track when the spell can be cast again Added a constant TimeSpan m_DispelCooldown set to 30 seconds
Added randomization:
Added a 15% chance to cast the spell even when conditions are met This significantly reduces how often the spell will be cast
Made evil detection more strict:
Changed the karma threshold from any negative value to significantly negative (-5000) This ensures only truly evil creatures are targeted
Added cooldown enforcement:
Check if the current time is past the cooldown before allowing another cast Set the next available cast time when the spell is selected
> Reworked PaladinAI.cs

- Scripts/Mobiles/AI/Magical AI/MageAI.cs
Death Ray should not be casted in any circumstances
> No More Death Ray

- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/ExodusBoss/ExodusBossAltar.cs
- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/ExodusBoss/PieczecExodusBoss1.cs
- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/ExodusBoss/PieczecExodusBoss2.cs
- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/ExodusBoss/PieczecExodusBoss3.cs
> Set KeyDrop chance for ExodusAltar

- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/ImiennySmok/ImiennySmokAltar.cs
- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/ImiennySmok/PieczecNelderimDragon1.cs
- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/ImiennySmok/PieczecNelderimDragon2.cs
- Scripts/Nelderim/Mobiles/CustomPeerlessAltars/ImiennySmok/PieczecNelderimDragon3.cs
> Set KeyDrop chance for ImiennySmokAltar.cs

- Scripts/Nelderim/Mobiles/Guards/BaseNelderimGuard.cs
poprawki wzgledem traktowania petow/przywolancow, oraz innej strazy.
> Poprawki straznika-pajaka: nie atakuje krasnali/tamaelow swojej frakcji,

- Scripts/Items/Functional/TwistedWealdAltar.cs
- Scripts/Items/Quest/PieczecDreadHorn1.cs
- Scripts/Items/Quest/PieczecDreadHorn2.cs
- Scripts/Items/Quest/PieczecDreadHorn3.cs
- Scripts/Mobiles/Named/Gnaw.cs
- Scripts/Mobiles/Named/Irk.cs
- Scripts/Mobiles/Named/LadyLissith.cs
- Scripts/Mobiles/Named/LadySabrix.cs
- Scripts/Mobiles/Normal/Wisp.cs
- Scripts/Nelderim/Mobiles/NewPets/UpadlyJednorozec.cs
Usunieto stare klucze z dropu
Dodano Drop kluczy w regionie (do poprawy)
> Dodano nowe pieczeci dla DH

- Data/CliLoc.csv
- Scripts/Mobiles/Normal/Triton.cs
- Scripts/Nelderim/Items/Artifacts/Rising Tide/CaptainsHook.cs
- Scripts/Nelderim/Items/Artifacts/Rising Tide/ScrollOfResurrection.cs
- Scripts/Quests/ProfessionalBountyQuest/BountyQuestSpawner.cs
- Scripts/Services/City Loyalty System/CityLoyaltySystem.cs
- Scripts/Services/City Loyalty System/Gumps.cs
- Scripts/Services/City Loyalty System/Items/Banners.cs
- Scripts/Services/City Loyalty System/Setup.cs
- Scripts/Services/Dungeons/BlackthornDungeon/InvasionSpawner/InvasionController.cs
- Scripts/Services/PointsSystems/PlayerMobileProps.cs
- Scripts/Services/Seasonal Events/ArtisanFestival/ArtisanFestivalEvent.cs
- Scripts/Services/Seasonal Events/RisingTide/BlackMarketMerchant.cs
- Scripts/Services/Seasonal Events/RisingTide/Rewards.cs
- Scripts/Services/Seasonal Events/RisingTide/RewardsGump.cs
- Scripts/Services/Town Cryer/Gumps/TownCryerGump.cs
- Scripts/Services/Town Cryer/TownCryerSystem.cs
Lokalizacja NPC dopasowana do Nelderim
Dodano 2 nowe rewardy zamiast 4 tytułów
Przetłumaczono cliloci
Tryton nie będzie mieć umiejętności Healing (bo nie chcemy tego)
Dostosowałem też wszystkie miasta z City pod nasze lokacje, które odnoszą się do multum innych rzeczy też
> Rising tide

- Scripts/Nelderim/Services/AFK.cs
Komedna [afk zamieniona na emota informująca o AFK, np.: *drzemie*
AIowane
> Emota informująca o AFK, np.: *drzemie*
